// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Web.Features.Aprovador
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CN08 - Aprovar Reembolso", Description="\tEsta funcionalidade tem o objetivo de permitir que o aprovador aprove uma solici" +
        "tação de reembolso.", SourceFile="Features\\Aprovador\\Aprovar Reembolso.feature", SourceLine=1)]
    public partial class CN08_AprovarReembolsoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Aprovar Reembolso.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "CN08 - Aprovar Reembolso", "\tEsta funcionalidade tem o objetivo de permitir que o aprovador aprove uma solici" +
                    "tação de reembolso.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN08 - aprovar_QdoOk", new string[] {
                "Browser_Chrome"}, SourceLine=5)]
        public virtual void CN08_Aprovar_QdoOk()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN08 - aprovar_QdoOk", new string[] {
                        "Browser_Chrome"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("Que o usuário Aprovador esteja logado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
 testRunner.And("Navegar até a pagina de aprovar reembolso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.When("Selecionar a quantidade de reembolsos 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 10
 testRunner.And("Na tabela clicar no botão Aprovar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And("Validar a mensagem Aprovar reembolso?", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("Clicar no botão Aprovar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.And("Validar a mensagem Reembolso aprovado com sucesso!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
 testRunner.And("Fechar o modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
 testRunner.Then("Verificar se a solicitação consta na lista para aprovar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN08 - aprovarMaisDeUmaSolicitacao_QdoOk", new string[] {
                "Browser_Chrome"}, SourceLine=17)]
        public virtual void CN08_AprovarMaisDeUmaSolicitacao_QdoOk()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN08 - aprovarMaisDeUmaSolicitacao_QdoOk", new string[] {
                        "Browser_Chrome"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("Que o usuário Aprovador esteja logado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 20
 testRunner.And("Navegar até a pagina de aprovar reembolso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
 testRunner.When("Selecionar a quantidade de reembolsos 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 22
 testRunner.And("clicar no botão Aprovar Selecionados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 23
 testRunner.And("Validar a mensagem Aprovar reembolsos selecionados?", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
 testRunner.And("Clicar no botão Aprovar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
 testRunner.And("Validar a mensagem Reembolso aprovado com sucesso!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.And("Fechar o modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
 testRunner.Then("Verificar se a solicitação consta na lista para aprovar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN08 - aprovarSolicitacao_QdoNaoTemSolicitacaoSelecionada_validarMensagemDeObriga" +
            "toriedade", new string[] {
                "Browser_Chrome"}, SourceLine=29)]
        public virtual void CN08_AprovarSolicitacao_QdoNaoTemSolicitacaoSelecionada_ValidarMensagemDeObrigatoriedade()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN08 - aprovarSolicitacao_QdoNaoTemSolicitacaoSelecionada_validarMensagemDeObriga" +
                    "toriedade", new string[] {
                        "Browser_Chrome"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("Que o usuário Aprovador esteja logado no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 32
 testRunner.And("Navegar até a pagina de aprovar reembolso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
 testRunner.When("clicar no botão Aprovar Selecionados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 34
 testRunner.Then("Validar a mensagem É necessário marcar pelo menos um reembolso para aprovar.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
