// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Web.Features.Comum
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CN03 - Esqueci minha senha", Description="\tFuncionalidade que valida a pagina de esqueci minha senha.", SourceFile="Features\\Comum\\Esqueci Minha Senha.feature", SourceLine=0)]
    public partial class CN03_EsqueciMinhaSenhaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Esqueci Minha Senha.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "CN03 - Esqueci minha senha", "\tFuncionalidade que valida a pagina de esqueci minha senha.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CN03_EsqueciMinhaSenha(string casoTeste, string username, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN03 - Esqueci minha senha", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("Que o sistema esteja aberto na pagina de login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 7
 testRunner.When("Clicar no link Esqueci minha senha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 8
 testRunner.And(string.Format("No campo Username/email inserir {0}", username), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.And("Clicar no botão submit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN03 - Esqueci minha senha, esqueciMinhaSenha_QdoNomeUsuarioOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"}, SourceLine=0)]
        public virtual void CN03_EsqueciMinhaSenha_EsqueciMinhaSenha_QdoNomeUsuarioOK()
        {
#line 5
this.CN03_EsqueciMinhaSenha("esqueciMinhaSenha_QdoNomeUsuarioOK", "admin", "You should receive an email shortly with further instructions.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN03 - Esqueci minha senha, esqueciMinhaSenha_QdoEmailOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"}, SourceLine=0)]
        public virtual void CN03_EsqueciMinhaSenha_EsqueciMinhaSenha_QdoEmailOK()
        {
#line 5
this.CN03_EsqueciMinhaSenha("esqueciMinhaSenha_QdoEmailOK", "admin.@prodesp.com.br", "You should receive an email shortly with further instructions.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN03 - Esqueci minha senha, esqueciMinhaSenha_QdoNomeUsuarioNOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"}, SourceLine=0)]
        public virtual void CN03_EsqueciMinhaSenha_EsqueciMinhaSenha_QdoNomeUsuarioNOK()
        {
#line 5
this.CN03_EsqueciMinhaSenha("esqueciMinhaSenha_QdoNomeUsuarioNOK", "reembolso", "You should receive an email shortly with further instructions.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN03 - Esqueci minha senha, esqueciMinhaSenha_QdoEmailNOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"}, SourceLine=0)]
        public virtual void CN03_EsqueciMinhaSenha_EsqueciMinhaSenha_QdoEmailNOK()
        {
#line 5
this.CN03_EsqueciMinhaSenha("esqueciMinhaSenha_QdoEmailNOK", "reembolso.@prodesp.com.br", "You should receive an email shortly with further instructions.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN03 - Esqueci minha senha, esqueciMinhaSenha_QdoNomeUsuarioEmailVazio", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"}, SourceLine=0)]
        public virtual void CN03_EsqueciMinhaSenha_EsqueciMinhaSenha_QdoNomeUsuarioEmailVazio()
        {
#line 5
this.CN03_EsqueciMinhaSenha("esqueciMinhaSenha_QdoNomeUsuarioEmailVazio", "", "Please specify username.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:EsqueciMinhaSenha"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
