// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Web.Features.Comum
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CN01 - Login", Description="\tFuncionalidade que valida a pagina de Login.", SourceFile="Features\\Comum\\Login.feature", SourceLine=0)]
    public partial class CN01_LoginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "CN01 - Login", "\tFuncionalidade que valida a pagina de Login.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CN01_Login(string casoTeste, string login, string senha, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN01 - Login", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("Que o sistema esteja aberto na pagina de login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 9
 testRunner.When(string.Format("Digitar login {0} e senha {1}", login, senha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 10
 testRunner.And("Clicar no botão Entrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioSenhaOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioSenhaOK()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioSenhaOK", "admin", "prodesp@123", "Meus reembolsos", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioNOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioNOK()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioNOK", "solicitante", "prodesp@123", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoSenhaNOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoSenhaNOK()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoSenhaNOK", "admin", "prodesp@12345", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioSenhaVazio", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioSenhaVazio()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioSenhaVazio", "", "", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioComCaracterEspecial", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioComCaracterEspecial()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioComCaracterEspecial", "<<prodesp@123>>", "prodesp@123", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoSenhaComCaracterEspecial", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoSenhaComCaracterEspecial()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoSenhaComCaracterEspecial", "prodesp@123", "<<prodesp@123>>", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioSenhaComCaracterEspecial", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioSenhaComCaracterEspecial()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioSenhaComCaracterEspecial", "<<prodesp@123>>", "<<prodesp@123>>", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioComSQLInjection", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioComSQLInjection()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioComSQLInjection", " or \"=", "prodesp@123", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoSenhaComSQLInjection", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoSenhaComSQLInjection()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoSenhaComSQLInjection", "admin", " or \"=", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSolicitante_QdoUsuarioSenhaComSQLInjection", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSolicitante_QdoUsuarioSenhaComSQLInjection()
        {
#line 7
this.CN01_Login("logarSolicitante_QdoUsuarioSenhaComSQLInjection", " or \"=", " or \"=", "Nome de usuário ou senha inválidos.", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarGestor_QdoUsuarioSenhaOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarGestor_QdoUsuarioSenhaOK()
        {
#line 7
this.CN01_Login("logarGestor_QdoUsuarioSenhaOK", "110000", "prodesp@123", "Meus reembolsos", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarSecretaria_QdoUsuarioSenhaOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarSecretaria_QdoUsuarioSenhaOK()
        {
#line 7
this.CN01_Login("logarSecretaria_QdoUsuarioSenhaOK", "admin", "prodesp@123", "Meus reembolsos", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN01 - Login, logarFinanceiro_QdoUsuarioSenhaOK", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"}, SourceLine=0)]
        public virtual void CN01_Login_LogarFinanceiro_QdoUsuarioSenhaOK()
        {
#line 7
this.CN01_Login("logarFinanceiro_QdoUsuarioSenhaOK", "120000", "prodesp@123", "Meus reembolsos", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:Login"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
