// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Web.Features.Comum
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CN02 - Logoff", Description="\tFuncionalidade destinada em fazer logof no sistema.", SourceFile="Features\\Comum\\Logoff.feature", SourceLine=0)]
    public partial class CN02_LogoffFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Logoff.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "CN02 - Logoff", "\tFuncionalidade destinada em fazer logof no sistema.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CN02_Logoff_MenuSuperiorDireito(string casoTeste, string usuario, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN02 - logoff_MenuSuperiorDireito", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 7
 testRunner.When("Clicar no menu com o icone da fotografica", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 8
 testRunner.And("Clicar no menu Sair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
 testRunner.Then(string.Format("O usuário é desconectado do sistema retornando para tela de login {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorDireito, logoffSolicitante_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=11)]
        public virtual void CN02_Logoff_MenuSuperiorDireito_LogoffSolicitante_QdoUsuarioLogado()
        {
#line 5
this.CN02_Logoff_MenuSuperiorDireito("logoffSolicitante_QdoUsuarioLogado", "solicitante", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorDireito, logoffAprovador_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=11)]
        public virtual void CN02_Logoff_MenuSuperiorDireito_LogoffAprovador_QdoUsuarioLogado()
        {
#line 5
this.CN02_Logoff_MenuSuperiorDireito("logoffAprovador_QdoUsuarioLogado", "aprovador", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorDireito, logoffSecretaria_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=11)]
        public virtual void CN02_Logoff_MenuSuperiorDireito_LogoffSecretaria_QdoUsuarioLogado()
        {
#line 5
this.CN02_Logoff_MenuSuperiorDireito("logoffSecretaria_QdoUsuarioLogado", "secretaria", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorDireito, logoffFinanceiro_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=11)]
        public virtual void CN02_Logoff_MenuSuperiorDireito_LogoffFinanceiro_QdoUsuarioLogado()
        {
#line 5
this.CN02_Logoff_MenuSuperiorDireito("logoffFinanceiro_QdoUsuarioLogado", "financeiro", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN02_Logoff_MenuSuperiorEsquerdo(string casoTeste, string usuario, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN02 - logoff_MenuSuperiorEsquerdo", @__tags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 20
 testRunner.When("Clicar no menu principal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 21
 testRunner.And("Clicar no menu Sair", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 22
 testRunner.Then(string.Format("O usuário é desconectado do sistema retornando para tela de login {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorEsquerdo, logoffSolicitante_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=24)]
        public virtual void CN02_Logoff_MenuSuperiorEsquerdo_LogoffSolicitante_QdoUsuarioLogado()
        {
#line 18
this.CN02_Logoff_MenuSuperiorEsquerdo("logoffSolicitante_QdoUsuarioLogado", "solicitante", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorEsquerdo, logoffAprovador_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=24)]
        public virtual void CN02_Logoff_MenuSuperiorEsquerdo_LogoffAprovador_QdoUsuarioLogado()
        {
#line 18
this.CN02_Logoff_MenuSuperiorEsquerdo("logoffAprovador_QdoUsuarioLogado", "aprovador", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorEsquerdo, logoffSecretaria_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=24)]
        public virtual void CN02_Logoff_MenuSuperiorEsquerdo_LogoffSecretaria_QdoUsuarioLogado()
        {
#line 18
this.CN02_Logoff_MenuSuperiorEsquerdo("logoffSecretaria_QdoUsuarioLogado", "secretaria", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN02 - logoff_MenuSuperiorEsquerdo, logoffFinanceiro_QdoUsuarioLogado", new string[] {
                "Browser_Chrome"}, SourceLine=24)]
        public virtual void CN02_Logoff_MenuSuperiorEsquerdo_LogoffFinanceiro_QdoUsuarioLogado()
        {
#line 18
this.CN02_Logoff_MenuSuperiorEsquerdo("logoffFinanceiro_QdoUsuarioLogado", "financeiro", "ENTRAR NO SISTEMA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
