// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Web.Features.Solicitante
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CN04 - Solicitar Reembolso", Description="\tEsta funcionalidade tem o objetivo de permitir que os colaboradores da Prodesp a" +
        "bra uma solicitação de reembolso.\r\n\tA solicitação pode ser aberta pelo próprio c" +
        "olaborador ou no caso de gestor pode ser aberta pela sua secretaria.", SourceFile="Features\\Solicitante\\Solicitar Reembolso.feature", SourceLine=1)]
    public partial class CN04_SolicitarReembolsoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Solicitar Reembolso.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "CN04 - Solicitar Reembolso", "\tEsta funcionalidade tem o objetivo de permitir que os colaboradores da Prodesp a" +
                    "bra uma solicitação de reembolso.\r\n\tA solicitação pode ser aberta pelo próprio c" +
                    "olaborador ou no caso de gestor pode ser aberta pela sua secretaria.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CN04_SolicitarReembolso(
                    string casoTeste, 
                    string usuario, 
                    string motivo, 
                    string qual, 
                    string descricao, 
                    string temRecurso, 
                    string recurso, 
                    string codDescricao, 
                    string despesas, 
                    string origem, 
                    string destino, 
                    string enviarpara, 
                    string mensageminterrogativa, 
                    string mensagemconfirmacao, 
                    string caminhoComprovante, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - Solicitar Reembolso", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 9
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 10
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.And(string.Format("Inserir despesas {0}, origem {1} e destino {2} e comprovante {3}", despesas, origem, destino, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
 testRunner.And(string.Format("Enviar para {0}", enviarpara), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 16
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensageminterrogativa), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 17
 testRunner.And("Confirmar o envio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
 testRunner.And(string.Format("Validar informações do envio ou rascunho {0}", descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoReuniaoEDespesaMetro_Salv" +
            "arComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoReuniaoEDespesaMetro_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoReuniaoEDespesaMetro_SalvarComoRascunho", "solicitante", "Reunião", "", "Reunião de projeto", "Sim", "Acessa SP", "44444", "MetroTrem", "Metrô Butantã", "CPTM Lapa", "Rascunho", "Meus reembolsos", "Reunião de projeto", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoCursoEDespesaOnibus_Salva" +
            "rComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoCursoEDespesaOnibus_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoCursoEDespesaOnibus_SalvarComoRascunho", "Solicitante", "Curso", "", "[[Valor Randomico]]", "Sim", "Poupatempo", "525252", "Onibus", "Prodesp - Sede", "Prodesp - Boa Vista", "Rascunho", "Meus reembolsos", "[[Valor Randomico]]", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoPalestraEDespesaEstaciona" +
            "mento_SalvarComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoPalestraEDespesaEstacionamento_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoPalestraEDespesaEstacionamento_SalvarComoRascunho", "solicitante", "Palestra", "", "Palestra Devops", "Sim", "ESP", "363636", "Estacionamento", "", "", "Rascunho", "Meus reembolsos", "Palestra Devops", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoEventoEDespesaTaxi_Salvar" +
            "ComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoEventoEDespesaTaxi_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoEventoEDespesaTaxi_SalvarComoRascunho", "solicitante", "Evento", "", "Amostra de projetos", "Sim", "Outro", "89898989", "Taxi", "Prodesp - Sede", "Prodesp - Boa Vista", "Rascunho", "Meus reembolsos", "Amostra de projetos", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoOutroEVeiculoProprio_Salv" +
            "arComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoOutroEVeiculoProprio_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoOutroEVeiculoProprio_SalvarComoRascunho", "solicitante", "Outro", "Assinar Documento", "Assinar documento na Boa Vista", "Sim", "Poupatempo", "5858585858", "VeiculoProprio", "", "", "Rascunho", "Meus reembolsos", "Assinar documento na Boa Vista", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_Sa" +
            "lvarComoRascunho", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_SalvarComoRascunho()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_SalvarComoRascunho", "solicitante", "Palestra", "", "Palestra Scrum", "Sim", "Poupatempo", "5858585858", "Pedagio", "", "", "Rascunho", "Meus reembolsos", "Palestra Scrum", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoReuniaoEDespesaMetro_Envi" +
            "arParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoReuniaoEDespesaMetro_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoReuniaoEDespesaMetro_EnviarParaAprovacao", "solicitante", "Reunião", "", "Reunião para inicio de testes", "Nao", "", "", "MetroTrem", "Metrô Butantã", "CPTM Lapa", "Aprovacao", "Enviar reembolso para aprovação?", "Reunião para inicio de testes", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoCursoEDespesaOnibus_Envia" +
            "rParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoCursoEDespesaOnibus_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoCursoEDespesaOnibus_EnviarParaAprovacao", "solicitante", "Curso", "", "[[Valor Randomico]]", "Nao", "", "", "Onibus", "Prodesp - Sede", "Prodesp - Boa Vista", "Aprovacao", "Enviar reembolso para aprovação?", "[[Valor Randomico]]", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoPalestraEDespesaEstaciona" +
            "mento_EnviarParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoPalestraEDespesaEstacionamento_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoPalestraEDespesaEstacionamento_EnviarParaAprovacao", "solicitante", "Palestra", "", "Palestra Gerenciamento de projetos", "Nao", "", "", "Estacionamento", "", "", "Aprovacao", "Enviar reembolso para aprovação?", "Palestra Gerenciamento de projetos", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoEventoEDespesaTaxi_Enviar" +
            "ParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoEventoEDespesaTaxi_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoEventoEDespesaTaxi_EnviarParaAprovacao", "solicitante", "Evento", "", "Amostra de projetos", "Nao", "", "", "Taxi", "Prodesp - Sede", "Prodesp - Boa Vista", "Aprovacao", "Enviar reembolso para aprovação?", "Amostra de projetos", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoOutroEVeiculoProprio_Envi" +
            "arParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoOutroEVeiculoProprio_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoOutroEVeiculoProprio_EnviarParaAprovacao", "solicitante", "Outro", "Assinar Documento", "Assinar documento na Boa Vista", "Nao", "", "", "VeiculoProprio", "", "", "Aprovacao", "Enviar reembolso para aprovação?", "Assinar documento na Boa Vista", "", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar Reembolso, solicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_En" +
            "viarParaAprovacao", new string[] {
                "Browser_Chrome",
                "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"}, SourceLine=1)]
        public virtual void CN04_SolicitarReembolso_SolicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_EnviarParaAprovacao()
        {
#line 7
this.CN04_SolicitarReembolso("solicitarReembolso_QdoMotivoReuniaoEDespesaPedagio_EnviarParaAprovacao", "solicitante", "Reunião", "", "Reunião externa", "Nao", "", "", "Pedagio", "", "", "Aprovacao", "Enviar reembolso para aprovação?", "Reunião externa", "C:\\Users\\40049906\\Desktop\\Print\\IconeExcluir.jpg", new string[] {
                        "Source:..\\..\\MassaDeDados\\MassaDeDados.xlsx:SolicitarReembolso"});
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoPossuiDiversasDespesasValidarSomaDeValores(string usuario, string motivo, string qual, string descricao, string temRecurso, string recurso, string codDescricao, string despesa_1, string despesa_2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - solicitarReembolso_QdoPossuiDiversasDespesasValidarSomaDeValores", @__tags);
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 27
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 28
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 29
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 30
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 31
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa_1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 32
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 34
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa_2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 35
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 36
 testRunner.Then("Validar o valor total de despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - solicitarReembolso_QdoPossuiDiversasDespesasValidarSomaDeValores, solicita" +
            "nte", new string[] {
                "Browser_Chrome"}, SourceLine=38)]
        public virtual void CN04_SolicitarReembolso_QdoPossuiDiversasDespesasValidarSomaDeValores_Solicitante()
        {
#line 25
this.CN04_SolicitarReembolso_QdoPossuiDiversasDespesasValidarSomaDeValores("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "MetroTrem", "Onibus", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoDeletarUmaDespesaValidarSubtracaoDeValores(string usuario, string motivo, string qual, string descricao, string temRecurso, string recurso, string codDescricao, string despesa_1, string despesa_2, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - solicitarReembolso_QdoDeletarUmaDespesaValidarSubtracaoDeValores", @__tags);
#line 42
this.ScenarioSetup(scenarioInfo);
#line 43
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 44
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 45
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 46
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 47
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 48
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa_1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 49
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 51
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa_2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 52
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 53
 testRunner.Then("Validar o valor total de despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 54
 testRunner.And("Excluir uma Despesa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 55
 testRunner.And("Validar o valor total de despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - solicitarReembolso_QdoDeletarUmaDespesaValidarSubtracaoDeValores, solicita" +
            "nte", new string[] {
                "Browser_Chrome"}, SourceLine=57)]
        public virtual void CN04_SolicitarReembolso_QdoDeletarUmaDespesaValidarSubtracaoDeValores_Solicitante()
        {
#line 42
this.CN04_SolicitarReembolso_QdoDeletarUmaDespesaValidarSubtracaoDeValores("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "MetroTrem", "Onibus", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoClicarNoBotaoVoltarValidarMensagemDeCancelamento(string usuario, string motivo, string qual, string descricao, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - solicitarReembolso_QdoClicarNoBotaoVoltarValidarMensagemDeCancelamento", @__tags);
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 63
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 64
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 65
 testRunner.And("Clicar no botão Voltar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 66
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 67
 testRunner.And("Clicar no botão OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - solicitarReembolso_QdoClicarNoBotaoVoltarValidarMensagemDeCancelamento, so" +
            "licitante", new string[] {
                "Browser_Chrome"}, SourceLine=69)]
        public virtual void CN04_SolicitarReembolso_QdoClicarNoBotaoVoltarValidarMensagemDeCancelamento_Solicitante()
        {
#line 61
this.CN04_SolicitarReembolso_QdoClicarNoBotaoVoltarValidarMensagemDeCancelamento("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Você perderá todos os dados não salvos.", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolsoEValidarLancamentosDuplicados(string usuario, string motivo, string qual, string descricao, string temRecurso, string recurso, string codDescricao, string despesa, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - Solicitar reembolso e validar lançamentos duplicados", @__tags);
#line 73
this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 75
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 76
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 77
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 78
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 79
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 80
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 81
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 82
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante <Caminho" +
                        "Comprovante>", despesa), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 83
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 84
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 85
 testRunner.And("Clicar no botão OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - Solicitar reembolso e validar lançamentos duplicados, solicitante", new string[] {
                "Browser_Chrome"}, SourceLine=87)]
        public virtual void CN04_SolicitarReembolsoEValidarLancamentosDuplicados_Solicitante()
        {
#line 73
this.CN04_SolicitarReembolsoEValidarLancamentosDuplicados("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "MetroTrem", "Já existe despesa", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoPossuiTodasDespesasEnviarParaAprovacao(
                    string usuario, 
                    string motivo, 
                    string qual, 
                    string descricao, 
                    string temRecurso, 
                    string recurso, 
                    string codDescricao, 
                    string despesa_1, 
                    string despesa_2, 
                    string despesa_3, 
                    string despesa_4, 
                    string despesa_5, 
                    string despesa_6, 
                    string caminhoComprovante, 
                    string enviarpara, 
                    string mensageminterrogativa, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - solicitarReembolso_QdoPossuiTodasDespesasEnviarParaAprovacao", @__tags);
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 93
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 94
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 95
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 96
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 97
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_1, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 98
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 99
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 100
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_2, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 101
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 102
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 103
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_3, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 104
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 105
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 106
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_4, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 107
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 108
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 109
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_5, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 110
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 111
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 112
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_6, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 113
 testRunner.And("Salvar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 114
 testRunner.And(string.Format("Enviar para {0}", enviarpara), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 115
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensageminterrogativa), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 116
 testRunner.And("Confirmar o envio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 117
 testRunner.And(string.Format("Validar informações do envio ou rascunho {0}", descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - solicitarReembolso_QdoPossuiTodasDespesasEnviarParaAprovacao, solicitante", new string[] {
                "Browser_Chrome"}, SourceLine=119)]
        public virtual void CN04_SolicitarReembolso_QdoPossuiTodasDespesasEnviarParaAprovacao_Solicitante()
        {
#line 91
this.CN04_SolicitarReembolso_QdoPossuiTodasDespesasEnviarParaAprovacao("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "Estacionamento", "MetroTrem", "Onibus", "Pedagio", "Taxi", "VeiculoProprio", "", "Aprovacao", "Enviar reembolso para aprovação?", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoPossuiDespesaVeiculo_ValidarKmAcimaDoPermitido(string usuario, string motivo, string qual, string descricao, string temRecurso, string recurso, string codDescricao, string despesas, string origem, string destino, string caminhoComprovante, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - SolicitarReembolso_QdoPossuiDespesaVeiculo_ValidarKmAcimaDoPermitido", @__tags);
#line 123
this.ScenarioSetup(scenarioInfo);
#line 124
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 125
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 126
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 127
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 128
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 129
 testRunner.And(string.Format("Inserir despesas {0}, origem {1} e destino {2} e comprovante {3}", despesas, origem, destino, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 130
 testRunner.Then(string.Format("É apresentanda a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - SolicitarReembolso_QdoPossuiDespesaVeiculo_ValidarKmAcimaDoPermitido, soli" +
            "citante", new string[] {
                "Browser_Chrome"}, SourceLine=132)]
        public virtual void CN04_SolicitarReembolso_QdoPossuiDespesaVeiculo_ValidarKmAcimaDoPermitido_Solicitante()
        {
#line 123
this.CN04_SolicitarReembolso_QdoPossuiDespesaVeiculo_ValidarKmAcimaDoPermitido("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "VeiculoProprio", "Prodesp - Sede", "Rua São José do Rio Preto, Araraquara - SP, Brasil", "Enviar reembolso para aprovação?", "A distancia total percorrida não pode ser superior a 150 km.", ((string[])(null)));
#line hidden
        }
        
        public virtual void CN04_SolicitarReembolso_QdoPossuiDespesaEstacionamento_ValidarCnpjProdesp(string usuario, string motivo, string qual, string descricao, string temRecurso, string recurso, string codDescricao, string despesa_1, string caminhoComprovante, string cNPJ, string mensagem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CN04 - solicitarReembolso_QdoPossuiDespesaEstacionamento_ValidarCnpjProdesp", @__tags);
#line 136
this.ScenarioSetup(scenarioInfo);
#line 137
 testRunner.Given(string.Format("Que o usuário {0} esteja logado no sistema", usuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 138
 testRunner.When("Iniciar uma nova solicitação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 139
 testRunner.And(string.Format("Informar o motivo {0}, qual {1} e descrição {2}", motivo, qual, descricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 140
 testRunner.And(string.Format("Informar se está associado a um recurso {0}, recurso {1} e Cod/Descrição {2}", temRecurso, recurso, codDescricao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 141
 testRunner.And("Clicar no botão adicionar despesas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 142
 testRunner.And(string.Format("Inserir despesas {0}, origem <origem> e destino <destino>  e comprovante {1}", despesa_1, caminhoComprovante), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 143
 testRunner.And(string.Format("Informar o {0} do estabelecimento", cNPJ), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 144
 testRunner.Then(string.Format("Validar a mensagem {0}", mensagem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CN04 - solicitarReembolso_QdoPossuiDespesaEstacionamento_ValidarCnpjProdesp, soli" +
            "citante", new string[] {
                "Browser_Chrome"}, SourceLine=146)]
        public virtual void CN04_SolicitarReembolso_QdoPossuiDespesaEstacionamento_ValidarCnpjProdesp_Solicitante()
        {
#line 136
this.CN04_SolicitarReembolso_QdoPossuiDespesaEstacionamento_ValidarCnpjProdesp("solicitante", "Outro", "Reunião externa", "Alinhamento de projetos", "Sim", "Poupatempo", "B0000957", "Estacionamento", "", "62.577.929/0001-35", "O CNPJ da Prodesp não pode ser informado no campo \"CNPJ do estabelecimento\".", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
